const fs = require('fs');
const path = require('path');

const artifactsDir = path.join(__dirname, '../artifacts/src');
const outputDir = path.join(__dirname, '../../frontend/config');
const outputFile = path.join(outputDir, 'abis.ts');

const targets = [
    { name: 'UniswapV2Factory', path: 'UniswapV2Factory.sol/UniswapV2Factory.json' },
    { name: 'UniswapV2Router02', path: 'UniswapV2Router02.sol/UniswapV2Router02.json' },
    { name: 'UniswapV2Pair', path: 'UniswapV2Pair.sol/UniswapV2Pair.json' },
    { name: 'UniswapV2ERC20', path: 'UniswapV2ERC20.sol/UniswapV2ERC20.json' }, // OR MockERC20? Using V2ERC20 for Pair logic.
    { name: 'MockERC20', path: 'test/MockERC20.sol/MockERC20.json' } // For Token logic 
];

let content = '// Generated by scripts/extractAbis.js\n\n';

targets.forEach(t => {
    const artifactPath = path.join(artifactsDir, t.path);
    if (fs.existsSync(artifactPath)) {
        const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
        content += `export const ${t.name}ABI = ${JSON.stringify(artifact.abi)} as const;\n\n`;
    } else {
        console.error(`Artifact not found: ${artifactPath}`);
    }
});

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputFile, content);
console.log(`ABIs written to ${outputFile}`);
